### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by drjdn** [pveber/OCaml-R#7] opened 2018-06-02 22:13 UTC
I'm getting the following error message:

```bash
     stubgen lib/stats/OCamlR_stats_stubs2.ml (exit 2)
(cd _build/default/lib/stats && ../../stubgen/stubgen.exe stats) > _build/default/lib/stats/OCamlR_stats_stubs2.ml
Error in as.environment(pos) : 
  no item called "package:stats" on the search list
Fatal error: exception OCamlR__R.Runtime_error(_, "Error in as.environment(pos) : \n  no item called \"package:stats\" on the search list\n")
Raised by primitive operation at file "lib/r.ml", line 988, characters 20-42
Called from file "stubgen/stubgen.ml", line 74, characters 15-61
Called from file "stubgen/stubgen.ml", line 90, characters 2-48
```
building with jbuilder from the latest git clone.  I'm on a Manjaro Linux machine running ocaml 4.06.1 via opam and R 3.5.0.  The machine is running gcc 8.1.0 but I'm certain that isn't the issue.

**Comment by pveber** [comment] 2018-06-03 13:58
Strange, this seems to suggest your `R` interpreter cannot find the (R) library `stats`... Just to be sure, could you run `R` on the command line and eval `require(stats)`?

**Comment by drjdn** [comment] 2018-06-03 14:49
Yes, here is the result:

```bash
[9] ~ $:~> /usr/local/R/bin/R -q -e "require(stats)"
> require(stats)
> 
> 
```

I use R regularly so I'm sure it is installed properly.  The stats library is loaded by default when you start the interpreter so it wouldn't run if not present.  I have R installed with root at /usr/local/R but I modified the jbuild (c_flags & c_library_flags) file in OCaml-R/lib accordingly.  Pretty sure that is correct as I don't think the build wouldn't have gotten this far otherwise.

Thanks,
Jason

**Comment by pveber** [comment] 2018-06-03 15:04
Thanks! From the command line, could you now run:
```
jbuilder utop lib/base
```
and then in the top-level:
```ocaml
open OCamlR;;
open Printf;;
R.strings_of_t @@ R.eval_string {|installed.packages()[,1]|};;
```

**Comment by drjdn** [comment] 2018-06-03 18:30
When running the above I get the following error when running the R.strings_of_t function:

```bash
Error in installed.packages() : 
  could not find function "installed.packages"
Exception:
OCamlR__R.Runtime_error (<abstr>,
 "Error in installed.packages() : \n  could not find function \"installed.packages\"\n").
```

Thanks,
Jason

**Comment by pveber** [comment] 2018-06-03 20:10
Right, `installed.packages` is from the `utils` package, which does not
seem to be loaded either. Is there any docker image for linux manjaro? It
would help to be able to reproduce the issue.

2018-06-03 20:30 GMT+02:00 jdn <notifications@github.com>:

**Comment by drjdn** [comment] 2018-06-04 18:06
I'm pretty sure I know what the problem is, just not how to fix it (jbuilder newb).  The issue is based on the following on my system:

```bash
[14] cube ~ $:~> pkg-config --cflags libR
-I/usr/local/R/lib64/R/include 
[15] cube ~ $:~> pkg-config --libs libR
-Wl,--export-dynamic -fopenmp -L/usr/local/lib64 -L/usr/local/R/lib64/R/lib -lR 
[16] cube ~ $:~> pkg-config --cflags libRmath
-I/usr/local/R/include 
[17] cube ~ $:~> pkg-config --libs libRmath 
-L/usr/local/R/lib64 -lRmath -lm 
```
on debian/ubuntu machines r-mathlib installs to /usr/include and /usr/lib.  That is not the default location if you install Rmath by source or arch/manjaro.  So some pkg-config magic needs to be done to OCaml-R/lib/config/discover.ml to add libRmath to the query.  My naive attempts haven't worked so I'm not sure how to set this up correctly at the moment. 

Thanks,
Jason

**Comment by drjdn** [comment] 2018-06-05 20:16
I've made a pull request that makes some minor fixes to the jbuild files so that it will build on distros other than ubuntu/debian (also some other very minor changes).  Unfortunately, this does not close this issue.  The problem is that there seems to be a change between R 3.4.4 and R 3.5.0 that breaks the c interface files.

**Comment by pveber** [comment] 2018-06-06 08:52
Hopefully  226decb should fix the compilation warnings. Could you confirm the problem is gone with R 3.5 or open an issue with more details?

**Comment by pveber** [comment] 2018-06-06 09:00
Woops, forgot a few ones. I'm fixing it.

**Comment by pveber** [comment] 2018-06-06 09:04
Ok, should be fixed with 93fdf60

**Comment by drjdn** [comment] 2018-06-06 16:54
Great, thanks!  I can confirm that I can now build with R 3.5.0.  Any plans to push the newest version to opam?

**Comment by pveber** [comment] 2018-06-06 17:02
Actually yes, I should have done that a long time ago. I'll try to do it in the next few days. Please give me some feedback about using the library, and if you want to contribute some wrappers let me know I'll help you.

**Closed by pveber** 2018-06-06 17:02 UTC
